In [3]:
import numpy as np
import pandas as pd
import sklearn
from xgboost import XGBRegressor
from pandas import DataFrame
from pandas import concat

In [4]:
df = pd.read_csv(r"C:\Users\King alagbe\Documents\Trainn.csv")

In [5]:
df.head

<bound method NDFrame.head of         Applicant_ID  form_field1  form_field2  form_field3  form_field4  \
0      Apcnt_1000000       3436.0      0.28505       1.6560       0.0000
1      Apcnt_1000004       3456.0      0.67400       0.2342       0.0000
2      Apcnt_1000008       3276.0      0.53845       3.1510       0.0000
3      Apcnt_1000012       3372.0      0.17005       0.5050       0.0000
4      Apcnt_1000016       3370.0      0.77270       1.1010       0.0000
...              ...          ...          ...          ...          ...
55995   Apcnt_999968       3740.0      0.01730       0.0000       0.0000
55996   Apcnt_999972       3360.0      2.01145       0.6252       0.0000
55997   Apcnt_999980       3500.0      0.76640       0.0000       0.0000
55998   Apcnt_999988       3280.0      0.05235       2.0916       2.2212
55999   Apcnt_999996       3522.0      0.46930       0.0000       0.0000

       form_field5  form_field6  form_field7  form_field8  form_field9  ...  \
0            0.000          0.0   10689720.0     252072.0    4272776.0  ...
1            0.000          0.0     898979.0     497531.0    9073814.0  ...
2            6.282          NaN     956940.0          NaN     192944.0  ...
3            0.000     192166.0    3044703.0     385499.0    3986472.0  ...
4            0.000       1556.0     214728.0     214728.0    1284089.0  ...
...            ...          ...          ...          ...          ...  ...
55995        0.000     770998.0    9637475.0    4047934.0   11641992.0  ...
55996        0.000          NaN     927765.0          NaN          NaN  ...
55997        0.000     118645.0    3662435.0    3662435.0    3585024.0  ...
55998        0.000          NaN    3458599.0          NaN     115533.0  ...
55999        0.000      98806.0    2053920.0     523983.0   14903368.0  ...

       form_field42  form_field43  form_field44  form_field45  form_field46  \
0          0.392854          2.02      0.711632           0.0           0.0
1          0.314281          8.08      0.183584           NaN           0.0
2          0.162965         18.18      0.791136           0.0           0.0
3          0.488884          2.02      0.685168           NaN           0.0
4          0.275000         12.12      0.438168           0.0           0.0
...             ...           ...           ...           ...           ...
55995      0.000000          9.09      0.730040           NaN           0.0
55996      0.297913         30.30      0.498208           NaN           0.0
55997      0.550000          3.03      0.450512           0.0           0.0
55998      0.942854          0.00      0.705048           1.0           0.0
55999      0.000000         13.13      0.292424           NaN           NaN

       form_field47  form_field48  form_field49  form_field50  default_status
0            charge           NaN      1.129518      0.044335              no
1            charge    349.805730      1.620483      0.322436              no
2            charge           NaN      1.513370      0.011640             yes
3            charge     89.940100      0.664452      0.082729              no
4            charge     97.887502      1.427891      0.045630              no
...             ...           ...           ...           ...             ...
55995       lending    591.048913      0.000000      0.241598              no
55996       lending           NaN      0.000000           NaN             yes
55997       lending   1252.474467      2.000000      0.163153              no
55998        charge           NaN      0.000000      0.002997              no
55999        charge   4986.188578      3.000000      0.678245              no

[56000 rows x 52 columns]>

In [6]:
df.shape

(56000, 52)

In [7]:
df.describe()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field48,form_field49,form_field50
count,53471.000000,52156.000000,55645.000000,55645.000000,55645.000000,4.264000e+04,5.083700e+04,4.264000e+04,4.799200e+04,5.564500e+04,...,12271.000000,17771.000000,54677.000000,55432.000000,50617.000000,24683.000000,40096.000000,3.511100e+04,55645.000000,4.494400e+04
mean,3491.795665,0.550737,1.052225,0.851979,1.956317,6.244479e+05,6.865210e+06,2.626690e+06,1.316002e+07,1.185585e+07,...,147.797977,108.117363,0.368215,6.634511,0.563377,0.072520,0.095371,3.052449e+05,1.049061,6.005862e+05
std,188.462426,0.820979,2.147768,3.157692,10.512396,1.433422e+06,1.912729e+07,3.927355e+06,1.977963e+07,2.669459e+07,...,45.085889,36.765769,0.412858,6.378946,0.196973,0.291146,0.335210,1.647757e+06,1.806160,5.842405e+06
min,2990.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.021000,0.000000,0.000000,0.000000,0.048528,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00
25%,3358.000000,0.070788,0.000000,0.000000,0.000000,1.400400e+04,6.869740e+05,1.929440e+05,1.368502e+06,4.500730e+05,...,136.191750,87.055500,0.000000,2.020000,0.411672,0.000000,0.000000,7.710079e+01,0.000000,4.560141e-02
50%,3484.000000,0.267575,0.062000,0.000000,0.000000,1.155330e+05,2.704328e+06,9.639420e+05,5.506295e+06,3.707559e+06,...,150.000000,118.441500,0.220000,5.050000,0.588648,0.000000,0.000000,3.181243e+02,0.000000,1.703996e-01
75%,3620.000000,0.719512,1.282000,0.000000,0.000000,5.259280e+05,6.993831e+06,3.751516e+06,1.694552e+07,1.326101e+07,...,167.754000,137.496750,0.628573,10.100000,0.753840,0.000000,0.000000,1.153022e+03,1.181754,4.993370e-01
max,3900.000000,18.015050,57.371600,91.672200,407.748600,5.313546e+07,2.158794e+09,1.037397e+08,3.200533e+08,2.191361e+09,...,645.450000,255.000000,2.200000,91.910000,0.800000,5.000000,5.000000,5.321014e+07,28.000000,2.307571e+08

In [8]:
for b in df:
    y = df[b].value_counts()
    print(y)

Apcnt_973904     1
Apcnt_963132     1
Apcnt_1022088    1
Apcnt_1056108    1
Apcnt_1038520    1
                ..
Apcnt_1129496    1
Apcnt_1028788    1
Apcnt_1139276    1
Apcnt_1196324    1
Apcnt_1056204    1
Name: Applicant_ID, Length: 56000, dtype: int64
3472.0    318
3488.0    311
3518.0    304
3502.0    293
3474.0    277
         ...
3020.0      1
3008.0      1
3000.0      1
3016.0      1
3046.0      1
Name: form_field1, Length: 449, dtype: int64
0.00000    4453
0.68005     181
0.09505     171
0.19505     153
0.06505     149
           ...
0.72325       1
0.13495       1
1.76795       1
2.65925       1
0.26065       1
Name: form_field2, Length: 20015, dtype: int64
0.0000     25728
1.5828       238
1.4132       186
0.1040       154
1.1776       145
           ...
8.1246         1
5.2224         1
10.6382        1
6.6216         1
6.6462         1
Name: form_field3, Length: 14617, dtype: int64
0.0000     47900
13.7790      645
1.0404       139
12.4272      117
0.9000       116
           ...
9.3510         1
1.2996         1
5.8212         1
22.6332        1
2.2734         1
Name: form_field4, Length: 2927, dtype: int64
0.0000     50322
12.7188      160
14.2452      121
25.4376       82
0.9666        47
           ...
64.8126        1
10.4166        1
16.3818        1
9.5850         1
15.3972        1
Name: form_field5, Length: 2991, dtype: int64
0.0           7454
192944.0      1670
115533.0      1009
385499.0       687
770998.0       456
              ...
3295608.0        1
2772014.0        1
1254914.0        1
3820369.0        1
13102687.0       1
Name: form_field6, Length: 5846, dtype: int64
0.0           2083
192944.0       335
115533.0       299
1927495.0      253
770998.0       240
              ...
18865722.0       1
6261733.0        1
30796352.0       1
8232796.0        1
9112714.0        1
Name: form_field7, Length: 23199, dtype: int64
0.0           1772
192944.0       663
770998.0       526
1927495.0      452
385499.0       438
              ...
4750468.0        1
13395993.0       1
7563327.0        1
5466228.0        1
9437140.0        1
Name: form_field8, Length: 12820, dtype: int64
115533.0      846
192944.0      678
385499.0      388
96472.0       283
308477.0      265
             ...
34972267.0      1
25182304.0      1
21317200.0      1
1778897.0       1
11696452.0      1
Name: form_field9, Length: 22650, dtype: int64
0.0           7190
115533.0       184
192944.0       153
77022.0         53
385499.0        53
              ...
933600.0         1
74747128.0       1
6982550.0        1
14996728.0       1
63562989.0       1
Name: form_field10, Length: 30942, dtype: int64
0.0          58
28786.0      51
38511.0      47
19450.0      43
57961.0      39
             ..
452018.0      1
1384451.0     1
1646637.0     1
3427868.0     1
5501238.0     1
Name: form_field11, Length: 9508, dtype: int64
0.0           3583
106975.0        33
389.0           32
3112.0          32
28786.0         31
              ...
9028301.0        1
4908013.0        1
2553007.0        1
19632441.0       1
11244434.0       1
Name: form_field12, Length: 16778, dtype: int64
0.0           9016
3112.0          26
38511.0         24
115533.0        23
462521.0        22
              ...
26221323.0       1
3232590.0        1
2753342.0        1
13110467.0       1
19996545.0       1
Name: form_field13, Length: 21960, dtype: int64
48187375     5021
34694910     5000
16576457     4427
21973443     4124
28141427     4087
             ...
314181685       1
26452000        1
21395389        1
134539151       1
96606205        1
Name: form_field14, Length: 1237, dtype: int64
115649700.0    75
134924650.0    74
77099800.0     65
53969860.0     63
48187375.0     63
               ..
65605628.0      1
89268498.0      1
57217232.0      1
195317678.0     1
71203338.0      1
Name: form_field15, Length: 23783, dtype: int64
0.0     35943
1.0      5123
2.0      1290
3.0       383
4.0       139
5.0        50
6.0        23
7.0         8
11.0        2
8.0         2
10.0        1
Name: form_field16, dtype: int64
0.0     36859
1.0      5653
2.0      1488
3.0       489
4.0       193
5.0        87
6.0        29
7.0        23
8.0        11
9.0         6
10.0        4
11.0        3
13.0        2
21.0        1
16.0        1
Name: form_field17, dtype: int64
0.0     37265
1.0      5909
2.0      1546
3.0       508
4.0       200
5.0        85
6.0        33
7.0        24
8.0        11
9.0         6
10.0        4
13.0        2
11.0        2
12.0        1
21.0        1
16.0        1
Name: form_field18, dtype: int64
0.0     33598
1.0     10233
2.0      5108
3.0      2865
4.0      1615
5.0       956
6.0       589
7.0       371
8.0       217
9.0       160
10.0       83
11.0       58
12.0       55
13.0       23
14.0       15
15.0       15
17.0        8
20.0        6
16.0        5
21.0        4
18.0        4
19.0        3
28.0        2
25.0        1
24.0        1
22.0        1
Name: form_field19, dtype: int64
0.0     31471
1.0     11000
2.0      5569
3.0      3030
4.0      1791
5.0      1040
6.0       630
7.0       394
8.0       248
9.0       169
10.0       95
11.0       58
12.0       52
13.0       27
14.0       17
15.0       16
16.0        8
17.0        7
20.0        6
21.0        4
18.0        4
19.0        4
29.0        1
25.0        1
24.0        1
22.0        1
28.0        1
Name: form_field20, dtype: int64
150.00    98
37.50     39
147.00    36
148.50    36
141.00    33
          ..
197.37     1
71.64      1
146.76     1
86.10      1
79.05      1
Name: form_field21, Length: 11101, dtype: int64
0.000        5205
15000.000     153
3750.000       39
14850.000      30
14700.000      29
             ...
5488.635        1
7283.175        1
3544.485        1
9803.160        1
2944.515        1
Name: form_field22, Length: 23583, dtype: int64
0.000        4785
15000.000     119
3750.000       52
14700.000      32
12000.000      26
             ...
442.560         1
11235.000       1
551.205         1
5368.185        1
5881.575        1
Name: form_field23, Length: 16619, dtype: int64
0.000      3262
150.000      44
0.030        29
0.045        28
0.135        27
           ...
319.365       1
144.660       1
160.635       1
462.600       1
153.825       1
Name: form_field24, Length: 12571, dtype: int64
274.5     275
228.0     265
411.0     261
364.5     250
183.0     247
         ...
6481.5      1
7281.0      1
6781.5      1
8866.5      1
5340.0      1
Name: form_field25, Length: 5014, dtype: int64
549.0      387
639.0      383
456.0      370
366.0      369
1005.0     367
          ...
57306.0      1
63783.0      1
56211.0      1
38415.0      1
46263.0      1
Name: form_field26, Length: 594, dtype: int64
426.0      429
366.0      427
304.0      407
244.0      400
182.0      395
          ...
29200.0      1
26280.0      1
38812.0      1
24638.0      1
26220.0      1
Name: form_field27, Length: 558, dtype: int64
60772.0    15407
0.0        11546
60.0        8973
122.0       2356
182.0       1430
           ...
5414.0         1
6022.0         1
7056.0         1
5780.0         1
6510.0         1
Name: form_field28, Length: 95, dtype: int64
11133.0    277
12135.0    273
11772.0    269
12045.0    268
11862.0    268
          ...
61593.0      1
60408.0      1
53655.0      1
56757.0      1
63510.0      1
Name: form_field29, Length: 654, dtype: int64
7422.0     316
7604.0     291
7544.0     287
7482.0     267
7726.0     265
          ...
14174.0      1
14966.0      1
15696.0      1
16546.0      1
14660.0      1
Name: form_field30, Length: 274, dtype: int64
6297.0     137
6204.0     134
11316.0    128
12045.0    126
11499.0    125
          ...
37413.0      1
28560.0      1
32760.0      1
43617.0      1
32211.0      1
Name: form_field31, Length: 394, dtype: int64
12.0      233
8.0       219
26.0      210
18.0      207
10.0      206
         ...
5476.0      1
6216.0      1
5432.0      1
4462.0      1
8426.0      1
Name: form_field32, Length: 2620, dtype: int64
0.1666      2338
0.6666      1141
0.3334      1088
0.5000      1073
0.8334       993
            ...
111.5000       1
118.3334       1
95.0000        1
67.8334        1
119.8334       1
Name: form_field33, Length: 554, dtype: int64
0.0     46890
1.0      6377
2.0      1510
3.0       532
4.0       170
5.0        67
6.0        32
7.0        27
8.0        12
9.0        10
13.0        4
10.0        4
15.0        3
11.0        2
14.0        2
12.0        1
17.0        1
21.0        1
Name: form_field34, dtype: int64
0.0     28090
1.0      3580
2.0       786
3.0       251
4.0        95
5.0        30
6.0        15
7.0         2
10.0        1
9.0         1
8.0         1
Name: form_field35, dtype: int64
8.0      6563
6.0      6476
4.0      6253
10.0     5574
12.0     4710
         ...
112.0       1
200.0       1
138.0       1
134.0       1
118.0       1
Name: form_field36, Length: 66, dtype: int64
0.0      11410
2.0       6899
4.0       5103
6.0       4447
8.0       3960
10.0      3499
12.0      2960
14.0      2539
16.0      2026
18.0      1619
20.0      1299
22.0      1026
24.0       798
26.0       641
28.0       493
30.0       391
32.0       285
34.0       226
36.0       186
38.0       162
40.0       104
42.0        90
46.0        63
44.0        59
48.0        52
50.0        37
52.0        26
54.0        24
60.0        19
56.0        17
58.0        16
62.0        14
64.0         8
66.0         7
70.0         6
74.0         5
84.0         4
68.0         4
80.0         3
90.0         3
72.0         3
86.0         3
82.0         3
104.0        2
76.0         2
102.0        1
92.0         1
96.0         1
100.0        1
88.0         1
106.0        1
78.0         1
Name: form_field37, dtype: int64
4.0      8448
2.0      7976
6.0      7628
8.0      6509
10.0     4956
0.0      4864
12.0     3769
14.0     2862
16.0     2120
18.0     1600
20.0     1174
22.0      892
24.0      686
26.0      491
28.0      385
30.0      281
32.0      204
34.0      150
36.0      125
38.0      118
40.0       80
42.0       60
44.0       43
46.0       38
48.0       26
52.0       19
50.0       18
56.0       15
54.0       15
62.0       11
58.0        9
68.0        6
80.0        6
72.0        6
64.0        5
60.0        5
70.0        5
66.0        5
86.0        4
78.0        4
74.0        4
76.0        3
90.0        3
110.0       2
106.0       2
118.0       1
142.0       1
98.0        1
156.0       1
100.0       1
132.0       1
102.0       1
96.0        1
104.0       1
84.0        1
94.0        1
150.0       1
82.0        1
Name: form_field38, dtype: int64
0.0     48194
1.0      2941
2.0       472
3.0        91
4.0        34
5.0        20
6.0        15
7.0         7
13.0        3
9.0         3
8.0         3
15.0        2
10.0        2
21.0        1
11.0        1
Name: form_field39, dtype: int64
150.0000    1610
75.0000       10
155.3505       4
153.8985       4
188.3730       3
            ...
128.5455       1
97.8660        1
190.3365       1
89.1930        1
120.0000       1
Name: form_field40, Length: 9848, dtype: int64
150.0000    488
0.0000       41
75.0000      25
124.9995     21
100.0005     19
           ...
144.5445      1
141.3990      1
117.6750      1
129.5865      1
32.4255       1
Name: form_field41, Length: 14375, dtype: int64
0.000000    16961
1.100000     2459
0.550000     1540
0.366663     1081
0.275000      908
            ...
0.597828        1
0.760001        1
0.162294        1
0.373582        1
0.830192        1
Name: form_field42, Length: 986, dtype: int64
0.00     6942
1.01     5790
2.02     4853
3.03     4413
4.04     4046
5.05     3677
6.06     3368
7.07     3097
8.08     2740
9.09     2395
10.10    2096
11.11    1905
12.12    1560
13.13    1399
14.14    1164
15.15     952
16.16     830
17.17     650
18.18     579
19.19     503
20.20     391
21.21     375
22.22     336
23.23     230
24.24     191
25.25     162
26.26     142
27.27     107
28.28      76
29.29      74
30.30      56
31.31      49
32.32      44
33.33      39
34.34      34
36.36      27
35.35      23
39.39      18
37.37      17
38.38      13
40.40       9
41.41       8
43.43       7
46.46       6
45.45       5
51.51       5
44.44       4
47.47       4
48.48       3
53.53       3
42.42       3
50.50       3
49.49       3
78.78       1
61.61       1
57.57       1
91.91       1
52.52       1
58.58       1
Name: form_field43, dtype: int64
0.800000    6572
0.505264      17
0.400000      14
0.786184       7
0.799864       7
            ...
0.311440       1
0.253608       1
0.532448       1
0.315176       1
0.375000       1
Name: form_field44, Length: 33238, dtype: int64
0.0    23075
1.0     1452
2.0      136
3.0       16
5.0        2
4.0        2
Name: form_field45, dtype: int64
0.0    36730
1.0     2964
2.0      354
3.0       41
4.0        6
5.0        1
Name: form_field46, dtype: int64
charge     36373
lending    19627
Name: form_field47, dtype: int64
0.000000       1416
7.674220         15
7.701687         11
7.700626         10
7.696985          9
               ...
1845.508090       1
1664.606140       1
73.234571         1
285.261474        1
210.623539        1
Name: form_field48, Length: 32115, dtype: int64
0.000000    29853
1.000000     4241
2.000000     1985
3.000000     1180
4.000000      667
            ...
0.498206        1
0.580046        1
1.029533        1
4.379818        1
0.781250        1
Name: form_field49, Length: 13207, dtype: int64
0.000000    19
0.016683     5
0.005561     5
0.006970     5
0.009990     5
            ..
0.466162     1
0.051705     1
0.099353     1
0.058151     1
0.015136     1
Name: form_field50, Length: 44746, dtype: int64
no     42285
yes    13715
Name: default_status, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['form_field47'] = le.fit_transform(df['form_field47'])
df['default_status'] = le.fit_transform(df['default_status'])

In [10]:
df.head

<bound method NDFrame.head of         Applicant_ID  form_field1  form_field2  form_field3  form_field4  \
0      Apcnt_1000000       3436.0      0.28505       1.6560       0.0000
1      Apcnt_1000004       3456.0      0.67400       0.2342       0.0000
2      Apcnt_1000008       3276.0      0.53845       3.1510       0.0000
3      Apcnt_1000012       3372.0      0.17005       0.5050       0.0000
4      Apcnt_1000016       3370.0      0.77270       1.1010       0.0000
...              ...          ...          ...          ...          ...
55995   Apcnt_999968       3740.0      0.01730       0.0000       0.0000
55996   Apcnt_999972       3360.0      2.01145       0.6252       0.0000
55997   Apcnt_999980       3500.0      0.76640       0.0000       0.0000
55998   Apcnt_999988       3280.0      0.05235       2.0916       2.2212
55999   Apcnt_999996       3522.0      0.46930       0.0000       0.0000

       form_field5  form_field6  form_field7  form_field8  form_field9  ...  \
0            0.000          0.0   10689720.0     252072.0    4272776.0  ...
1            0.000          0.0     898979.0     497531.0    9073814.0  ...
2            6.282          NaN     956940.0          NaN     192944.0  ...
3            0.000     192166.0    3044703.0     385499.0    3986472.0  ...
4            0.000       1556.0     214728.0     214728.0    1284089.0  ...
...            ...          ...          ...          ...          ...  ...
55995        0.000     770998.0    9637475.0    4047934.0   11641992.0  ...
55996        0.000          NaN     927765.0          NaN          NaN  ...
55997        0.000     118645.0    3662435.0    3662435.0    3585024.0  ...
55998        0.000          NaN    3458599.0          NaN     115533.0  ...
55999        0.000      98806.0    2053920.0     523983.0   14903368.0  ...

       form_field42  form_field43  form_field44  form_field45  form_field46  \
0          0.392854          2.02      0.711632           0.0           0.0
1          0.314281          8.08      0.183584           NaN           0.0
2          0.162965         18.18      0.791136           0.0           0.0
3          0.488884          2.02      0.685168           NaN           0.0
4          0.275000         12.12      0.438168           0.0           0.0
...             ...           ...           ...           ...           ...
55995      0.000000          9.09      0.730040           NaN           0.0
55996      0.297913         30.30      0.498208           NaN           0.0
55997      0.550000          3.03      0.450512           0.0           0.0
55998      0.942854          0.00      0.705048           1.0           0.0
55999      0.000000         13.13      0.292424           NaN           NaN

       form_field47  form_field48  form_field49  form_field50  default_status
0                 0           NaN      1.129518      0.044335               0
1                 0    349.805730      1.620483      0.322436               0
2                 0           NaN      1.513370      0.011640               1
3                 0     89.940100      0.664452      0.082729               0
4                 0     97.887502      1.427891      0.045630               0
...             ...           ...           ...           ...             ...
55995             1    591.048913      0.000000      0.241598               0
55996             1           NaN      0.000000           NaN               1
55997             1   1252.474467      2.000000      0.163153               0
55998             0           NaN      0.000000      0.002997               0
55999             0   4986.188578      3.000000      0.678245               0

[56000 rows x 52 columns]>

In [11]:
miss_data = df.isnull()
miss_data.head

<bound method NDFrame.head of        Applicant_ID  form_field1  form_field2  form_field3  form_field4  \
0             False        False        False        False        False
1             False        False        False        False        False
2             False        False        False        False        False
3             False        False        False        False        False
4             False        False        False        False        False
...             ...          ...          ...          ...          ...
55995         False        False        False        False        False
55996         False        False        False        False        False
55997         False        False        False        False        False
55998         False        False        False        False        False
55999         False        False        False        False        False

       form_field5  form_field6  form_field7  form_field8  form_field9  ...  \
0            False        False        False        False        False  ...
1            False        False        False        False        False  ...
2            False         True        False         True        False  ...
3            False        False        False        False        False  ...
4            False        False        False        False        False  ...
...            ...          ...          ...          ...          ...  ...
55995        False        False        False        False        False  ...
55996        False         True        False         True         True  ...
55997        False        False        False        False        False  ...
55998        False         True        False         True        False  ...
55999        False        False        False        False        False  ...

       form_field42  form_field43  form_field44  form_field45  form_field46  \
0             False         False         False         False         False
1             False         False         False          True         False
2             False         False         False         False         False
3             False         False         False          True         False
4             False         False         False         False         False
...             ...           ...           ...           ...           ...
55995         False         False         False          True         False
55996         False         False         False          True         False
55997         False         False         False         False         False
55998         False         False         False         False         False
55999         False         False         False          True          True

       form_field47  form_field48  form_field49  form_field50  default_status
0             False          True         False         False           False
1             False         False         False         False           False
2             False          True         False         False           False
3             False         False         False         False           False
4             False         False         False         False           False
...             ...           ...           ...           ...             ...
55995         False         False         False         False           False
55996         False          True         False          True           False
55997         False         False         False         False           False
55998         False          True         False         False           False
55999         False         False         False         False           False

[56000 rows x 52 columns]>

In [12]:
for i in miss_data:
    x = miss_data[i].value_counts()
    print(x)

False    56000
Name: Applicant_ID, dtype: int64
False    53471
True      2529
Name: form_field1, dtype: int64
False    52156
True      3844
Name: form_field2, dtype: int64
False    55645
True       355
Name: form_field3, dtype: int64
False    55645
True       355
Name: form_field4, dtype: int64
False    55645
True       355
Name: form_field5, dtype: int64
False    42640
True     13360
Name: form_field6, dtype: int64
False    50837
True      5163
Name: form_field7, dtype: int64
False    42640
True     13360
Name: form_field8, dtype: int64
False    47992
True      8008
Name: form_field9, dtype: int64
False    55645
True       355
Name: form_field10, dtype: int64
True     31421
False    24579
Name: form_field11, dtype: int64
False    46105
True      9895
Name: form_field12, dtype: int64
False    50111
True      5889
Name: form_field13, dtype: int64
False    56000
Name: form_field14, dtype: int64
False    33525
True     22475
Name: form_field15, dtype: int64
False    42964
True     13036
Name: form_field16, dtype: int64
False    44849
True     11151
Name: form_field17, dtype: int64
False    45598
True     10402
Name: form_field18, dtype: int64
False    55996
True         4
Name: form_field19, dtype: int64
False    55645
True       355
Name: form_field20, dtype: int64
False    40146
True     15854
Name: form_field21, dtype: int64
False    35600
True     20400
Name: form_field22, dtype: int64
True     28123
False    27877
Name: form_field23, dtype: int64
False    42703
True     13297
Name: form_field24, dtype: int64
False    50550
True      5450
Name: form_field25, dtype: int64
False    48562
True      7438
Name: form_field26, dtype: int64
False    46701
True      9299
Name: form_field27, dtype: int64
False    55645
True       355
Name: form_field28, dtype: int64
False    55645
True       355
Name: form_field29, dtype: int64
False    30491
True     25509
Name: form_field30, dtype: int64
True     39408
False    16592
Name: form_field31, dtype: int64
False    50550
True      5450
Name: form_field32, dtype: int64
False    54744
True      1256
Name: form_field33, dtype: int64
False    55645
True       355
Name: form_field34, dtype: int64
False    32852
True     23148
Name: form_field35, dtype: int64
False    54005
True      1995
Name: form_field36, dtype: int64
False    50550
True      5450
Name: form_field37, dtype: int64
False    55645
True       355
Name: form_field38, dtype: int64
False    51789
True      4211
Name: form_field39, dtype: int64
True     43729
False    12271
Name: form_field40, dtype: int64
True     38229
False    17771
Name: form_field41, dtype: int64
False    54677
True      1323
Name: form_field42, dtype: int64
False    55432
True       568
Name: form_field43, dtype: int64
False    50617
True      5383
Name: form_field44, dtype: int64
True     31317
False    24683
Name: form_field45, dtype: int64
False    40096
True     15904
Name: form_field46, dtype: int64
False    56000
Name: form_field47, dtype: int64
False    35111
True     20889
Name: form_field48, dtype: int64
False    55645
True       355
Name: form_field49, dtype: int64
False    44944
True     11056
Name: form_field50, dtype: int64
False    56000
Name: default_status, dtype: int64

In [13]:
df.isnull().values.sum().sum()

528773

In [14]:
k  = df.iloc[:, 1:51]
k

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,3436.0,0.28505,1.6560,0.0000,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,...,NaN,0.392854,2.02,0.711632,0.0,0.0,0,NaN,1.129518,0.044335
1,3456.0,0.67400,0.2342,0.0000,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,...,NaN,0.314281,8.08,0.183584,NaN,0.0,0,349.805730,1.620483,0.322436
2,3276.0,0.53845,3.1510,0.0000,6.282,NaN,956940.0,NaN,192944.0,1079864.0,...,NaN,0.162965,18.18,0.791136,0.0,0.0,0,NaN,1.513370,0.011640
3,3372.0,0.17005,0.5050,0.0000,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,...,NaN,0.488884,2.02,0.685168,NaN,0.0,0,89.940100,0.664452,0.082729
4,3370.0,0.77270,1.1010,0.0000,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,...,NaN,0.275000,12.12,0.438168,0.0,0.0,0,97.887502,1.427891,0.045630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,3740.0,0.01730,0.0000,0.0000,0.000,770998.0,9637475.0,4047934.0,11641992.0,19910965.0,...,NaN,0.000000,9.09,0.730040,NaN,0.0,1,591.048913,0.000000,0.241598
55996,3360.0,2.01145,0.6252,0.0000,0.000,NaN,927765.0,NaN,NaN,1849306.0,...,136.5135,0.297913,30.30,0.498208,NaN,0.0,1,NaN,0.000000,NaN
55997,3500.0,0.76640,0.0000,0.0000,0.000,118645.0,3662435.0,3662435.0,3585024.0,704090.0,...,NaN,0.550000,3.03,0.450512,0.0,0.0,1,1252.474467,2.000000,0.163153
55998,3280.0,0.05235,2.0916,2.2212,0.000,NaN,3458599.0,NaN,115533.0,3458599.0,...,150.0000,0.942854,0.00,0.705048,1.0,0.0,0,NaN,0.000000,0.002997
55999,3522.0,0.46930,0.0000,0.0000,0.000,98806.0,2053920.0,523983.0,14903368.0,5430440.0,...,NaN,0.000000,13.13,0.292424,NaN,NaN,0,4986.188578,3.000000,0.678245

In [15]:
#i filled in my NaNs with median, adjust please if wrong
med = df.median()
k.fillna(med, inplace = True)

In [16]:
k.isnull().values.sum().sum()

0

In [17]:
k.isnull().values.any()

False

In [18]:
k.describe()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
count,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000,5.600000e+04,5.600000e+04,5.600000e+04,5.600000e+04,5.600000e+04,...,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000,56000.000000,5.600000e+04,56000.000000,5.600000e+04
mean,3491.443607,0.531300,1.045948,0.846578,1.943915,5.030354e+05,6.481592e+06,2.230006e+06,1.206553e+07,1.180420e+07,...,115.165246,0.364714,6.618440,0.565806,0.031964,0.068286,0.350482,1.915018e+05,1.042410,4.820133e+05
std,184.164752,0.795529,2.142391,3.148393,10.480172,1.269466e+06,1.826393e+07,3.499505e+06,1.850582e+07,2.661770e+07,...,21.260974,0.408573,6.348499,0.187415,0.196615,0.286885,0.477125,1.313031e+06,1.802351,5.239443e+06
min,2990.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.048528,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00
25%,3366.000000,0.080150,0.000000,0.000000,0.000000,3.501000e+04,8.145660e+05,3.294830e+05,1.831315e+06,4.609650e+05,...,118.441500,0.000000,2.020000,0.428256,0.000000,0.000000,0.000000,1.939907e+02,0.000000,6.719678e-02
50%,3484.000000,0.267575,0.062000,0.000000,0.000000,1.155330e+05,2.704328e+06,9.639420e+05,5.506295e+06,3.707559e+06,...,118.441500,0.220000,5.050000,0.588648,0.000000,0.000000,0.000000,3.181243e+02,0.000000,1.703996e-01
75%,3610.000000,0.675700,1.270800,0.000000,0.000000,3.023502e+05,6.335740e+06,2.361230e+06,1.403308e+07,1.315909e+07,...,118.441500,0.611116,10.100000,0.739474,0.000000,0.000000,1.000000,5.096936e+02,1.158480,3.800000e-01
max,3900.000000,18.015050,57.371600,91.672200,407.748600,5.313546e+07,2.158794e+09,1.037397e+08,3.200533e+08,2.191361e+09,...,255.000000,2.200000,91.910000,0.800000,5.000000,5.000000,1.000000,5.321014e+07,28.000000,2.307571e+08

In [19]:
from sklearn.preprocessing import MinMaxScaler
names = df.iloc[:,1:51].columns
scaler = MinMaxScaler()
k = scaler.fit_transform(k)
k =pd.DataFrame(data=k, columns = names)
k

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,0.490110,0.015823,0.028864,0.00000,0.000000,0.000000,0.004952,0.002430,0.013350,0.005172,...,0.464476,0.178570,0.021978,0.882407,0.0,0.0,0.0,0.000006,0.040340,1.921277e-10
1,0.512088,0.037413,0.004082,0.00000,0.000000,0.000000,0.000416,0.004796,0.028351,0.001156,...,0.464476,0.142855,0.087912,0.179722,0.0,0.0,0.0,0.000007,0.057874,1.397297e-09
2,0.314286,0.029889,0.054923,0.00000,0.015407,0.002174,0.000443,0.009292,0.000603,0.000493,...,0.464476,0.074075,0.197802,0.988204,0.0,0.0,0.0,0.000006,0.054049,5.044122e-11
3,0.419780,0.009439,0.008802,0.00000,0.000000,0.003617,0.001410,0.003716,0.012456,0.001653,...,0.464476,0.222220,0.021978,0.847191,0.0,0.0,0.0,0.000002,0.023730,3.585092e-10
4,0.417582,0.042892,0.019191,0.00000,0.000000,0.000029,0.000099,0.002070,0.004012,0.000165,...,0.464476,0.125000,0.131868,0.518502,0.0,0.0,0.0,0.000002,0.050996,1.977398e-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55995,0.824176,0.000960,0.000000,0.00000,0.000000,0.014510,0.004464,0.039020,0.036375,0.009086,...,0.464476,0.000000,0.098901,0.906903,0.0,0.0,1.0,0.000011,0.000000,1.046981e-09
55996,0.406593,0.111654,0.010897,0.00000,0.000000,0.002174,0.000430,0.009292,0.017204,0.000844,...,0.535347,0.135415,0.329670,0.598399,0.0,0.0,1.0,0.000006,0.000000,7.384370e-10
55997,0.560440,0.042542,0.000000,0.00000,0.000000,0.002233,0.001697,0.035304,0.011201,0.000321,...,0.464476,0.250000,0.032967,0.534929,0.0,0.0,1.0,0.000024,0.071429,7.070317e-10
55998,0.318681,0.002906,0.036457,0.02423,0.000000,0.002174,0.001602,0.009292,0.000361,0.001578,...,0.588235,0.428570,0.000000,0.873645,0.2,0.0,0.0,0.000006,0.000000,1.298757e-11
55999,0.584615,0.026050,0.000000,0.00000,0.000000,0.001860,0.000951,0.005051,0.046565,0.002478,...,0.464476,0.000000,0.142857,0.324558,0.0,0.0,0.0,0.000094,0.107143,2.939214e-09

In [20]:
k.head

<bound method NDFrame.head of        form_field1  form_field2  form_field3  form_field4  form_field5  \
0         0.490110     0.015823     0.028864      0.00000     0.000000
1         0.512088     0.037413     0.004082      0.00000     0.000000
2         0.314286     0.029889     0.054923      0.00000     0.015407
3         0.419780     0.009439     0.008802      0.00000     0.000000
4         0.417582     0.042892     0.019191      0.00000     0.000000
...            ...          ...          ...          ...          ...
55995     0.824176     0.000960     0.000000      0.00000     0.000000
55996     0.406593     0.111654     0.010897      0.00000     0.000000
55997     0.560440     0.042542     0.000000      0.00000     0.000000
55998     0.318681     0.002906     0.036457      0.02423     0.000000
55999     0.584615     0.026050     0.000000      0.00000     0.000000

       form_field6  form_field7  form_field8  form_field9  form_field10  ...  \
0         0.000000     0.004952     0.002430     0.013350      0.005172  ...
1         0.000000     0.000416     0.004796     0.028351      0.001156  ...
2         0.002174     0.000443     0.009292     0.000603      0.000493  ...
3         0.003617     0.001410     0.003716     0.012456      0.001653  ...
4         0.000029     0.000099     0.002070     0.004012      0.000165  ...
...            ...          ...          ...          ...           ...  ...
55995     0.014510     0.004464     0.039020     0.036375      0.009086  ...
55996     0.002174     0.000430     0.009292     0.017204      0.000844  ...
55997     0.002233     0.001697     0.035304     0.011201      0.000321  ...
55998     0.002174     0.001602     0.009292     0.000361      0.001578  ...
55999     0.001860     0.000951     0.005051     0.046565      0.002478  ...

       form_field41  form_field42  form_field43  form_field44  form_field45  \
0          0.464476      0.178570      0.021978      0.882407           0.0
1          0.464476      0.142855      0.087912      0.179722           0.0
2          0.464476      0.074075      0.197802      0.988204           0.0
3          0.464476      0.222220      0.021978      0.847191           0.0
4          0.464476      0.125000      0.131868      0.518502           0.0
...             ...           ...           ...           ...           ...
55995      0.464476      0.000000      0.098901      0.906903           0.0
55996      0.535347      0.135415      0.329670      0.598399           0.0
55997      0.464476      0.250000      0.032967      0.534929           0.0
55998      0.588235      0.428570      0.000000      0.873645           0.2
55999      0.464476      0.000000      0.142857      0.324558           0.0

       form_field46  form_field47  form_field48  form_field49  form_field50
0               0.0           0.0      0.000006      0.040340  1.921277e-10
1               0.0           0.0      0.000007      0.057874  1.397297e-09
2               0.0           0.0      0.000006      0.054049  5.044122e-11
3               0.0           0.0      0.000002      0.023730  3.585092e-10
4               0.0           0.0      0.000002      0.050996  1.977398e-10
...             ...           ...           ...           ...           ...
55995           0.0           1.0      0.000011      0.000000  1.046981e-09
55996           0.0           1.0      0.000006      0.000000  7.384370e-10
55997           0.0           1.0      0.000024      0.071429  7.070317e-10
55998           0.0           0.0      0.000006      0.000000  1.298757e-11
55999           0.0           0.0      0.000094      0.107143  2.939214e-09

[56000 rows x 50 columns]>

In [21]:
c = df['default_status']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
#preprocess on my test.csv
dt = pd.read_csv(r"C:\Users\King alagbe\Documents\Testt.csv")

In [24]:
dt.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,...,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,...,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,...,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [25]:
le = LabelEncoder()
dt['form_field47'] = le.fit_transform(dt['form_field47'])

In [26]:
dt.isnull().values.sum().sum()

225629

In [27]:
med = dt.median()
dt.fillna(med, inplace = True)

In [28]:
names = dt.iloc[:, 1:51].columns
scaler = MinMaxScaler()
dt = scaler.fit_transform(dt.iloc[:, 1:51])
dt =pd.DataFrame(data=dt, columns = names)
dt.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,0.273523,0.015628,0.295315,0.000000,0.0,0.008686,0.000543,0.003687,0.000374,0.000000,...,0.557334,0.375000,0.010989,1.000000,0.0,0.0,0.0,2.579717e-06,0.000000,4.444680e-11
1,0.326039,0.057074,0.085712,0.043689,0.0,0.000000,0.012787,0.000432,0.001046,0.023651,...,0.089004,0.230770,0.043956,0.759052,0.2,0.0,1.0,2.579717e-06,0.021041,1.724046e-10
2,0.544858,0.012326,0.001737,0.000000,0.0,0.002398,0.003528,0.008452,0.003830,0.000000,...,0.557334,0.100000,0.000000,0.716591,0.0,0.0,0.0,2.579717e-06,0.000000,6.654544e-10
3,0.269147,0.012774,0.081155,0.000000,0.0,0.000000,0.000615,0.004174,0.001194,0.000638,...,0.557334,0.416665,0.021978,0.542270,0.0,0.0,0.0,7.427051e-07,0.032867,4.120640e-10
4,0.525164,0.093903,0.024081,0.012197,0.0,0.000412,0.001492,0.010137,0.005444,0.007432,...,0.557334,0.106385,0.252747,0.900061,0.0,0.0,1.0,1.073803e-05,0.068239,6.461410e-10

In [29]:
dt.head

<bound method NDFrame.head of        form_field1  form_field2  form_field3  form_field4  form_field5  \
0         0.273523     0.015628     0.295315     0.000000     0.000000
1         0.326039     0.057074     0.085712     0.043689     0.000000
2         0.544858     0.012326     0.001737     0.000000     0.000000
3         0.269147     0.012774     0.081155     0.000000     0.000000
4         0.525164     0.093903     0.024081     0.012197     0.000000
...            ...          ...          ...          ...          ...
23995     0.297593     0.016995     0.016496     0.024840     0.000000
23996     0.577681     0.042689     0.000000     0.000000     0.000000
23997     0.345733     0.002579     0.122734     0.000000     0.085394
23998     0.380744     0.033910     0.041770     0.000000     0.000000
23999     0.369803     0.020094     0.067079     0.032538     0.000000

       form_field6  form_field7  form_field8  form_field9  form_field10  ...  \
0         0.008686     0.000543     0.003687     0.000374      0.000000  ...
1         0.000000     0.012787     0.000432     0.001046      0.023651  ...
2         0.002398     0.003528     0.008452     0.003830      0.000000  ...
3         0.000000     0.000615     0.004174     0.001194      0.000638  ...
4         0.000412     0.001492     0.010137     0.005444      0.007432  ...
...            ...          ...          ...          ...           ...  ...
23995     0.002398     0.002958     0.008452     0.003830      0.002946  ...
23996     0.031015     0.006191     0.042051     0.062135      0.016794  ...
23997     0.002398     0.000064     0.008452     0.003830      0.000064  ...
23998     0.000000     0.003260     0.000332     0.000273      0.003296  ...
23999     0.002398     0.006881     0.008452     0.013080      0.006926  ...

       form_field41  form_field42  form_field43  form_field44  form_field45  \
0          0.557334      0.375000      0.010989      1.000000           0.0
1          0.089004      0.230770      0.043956      0.759052           0.2
2          0.557334      0.100000      0.000000      0.716591           0.0
3          0.557334      0.416665      0.021978      0.542270           0.0
4          0.557334      0.106385      0.252747      0.900061           0.0
...             ...           ...           ...           ...           ...
23995      0.437855      0.500000      0.000000      1.000000           0.0
23996      0.590580      0.000000      0.131868      0.177172           0.0
23997      0.557334      0.500000      0.010989      1.000000           0.0
23998      0.147362      0.200000      0.021978      0.617999           0.0
23999      0.530500      0.142855      0.032967      0.651501           0.0

       form_field46  form_field47  form_field48  form_field49  form_field50
0          0.000000           0.0  2.579717e-06      0.000000  4.444680e-11
1          0.000000           1.0  2.579717e-06      0.021041  1.724046e-10
2          0.000000           0.0  2.579717e-06      0.000000  6.654544e-10
3          0.000000           0.0  7.427051e-07      0.032867  4.120640e-10
4          0.000000           1.0  1.073803e-05      0.068239  6.461410e-10
...             ...           ...           ...           ...           ...
23995      0.052632           0.0  2.579717e-06      0.000000  6.654544e-10
23996      0.000000           0.0  3.459723e-05      0.125000  3.687452e-09
23997      0.000000           0.0  2.579717e-06      0.202294  6.654544e-10
23998      0.000000           0.0  2.250851e-07      0.034114  9.406937e-11
23999      0.052632           0.0  2.579717e-06      0.000000  1.552439e-09

[24000 rows x 50 columns]>

In [30]:
X_train, X_test, y_train, y_test = train_test_split(k, c , test_size = 0.3, random_state = 1)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((39200, 50), (16800, 50), (39200,), (16800,))

In [33]:
#my xgboost model, adjust if needed
from xgboost import XGBClassifier
model = XGBClassifier (max_depth = 7, learning_rate = 0.1, nround = 25, subsample= 0.3, nthread = 10, seed = 11)

In [35]:
model.fit(X_train,y_train)

XGBClassifier(max_depth=7, nround=25, nthread=10, seed=11, subsample=0.3)

In [36]:
pred = model.predict_proba(X_test)

In [37]:

preds = np.argmax(pred, axis = 1)

In [38]:
from sklearn.metrics import roc_auc_score
accuracy = roc_auc_score(y_test , preds)
print ('Accuracy: %.2f%%' % (accuracy * 100.0))

Accuracy: 68.62%

In [92]:
#my lightgbm model, adjust if needed
import lightgbm
from lightgbm import LGBMClassifier
mode = LGBMClassifier(max_depth = 8, learning_rate = 0.1, nround = 25, subsample= 0.3, nthread = 10, seed = 11)

In [93]:
mode.fit(X_train, y_train)

LGBMClassifier(max_depth=8, nround=25, nthread=10, seed=11, subsample=0.3)

In [94]:
pre = mode.predict_proba(X_test)

In [95]:
predsi = np.argmax(pre, axis = 1)

In [96]:
from sklearn.metrics import roc_auc_score
acc = roc_auc_score(y_test , predsi)
print ('Acc: %.2f%%' % (acc * 100.0))

Acc: 68.68%

In [39]:
#my deep learning model
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [286]:
models =Sequential()
models.add(Dense(10, input_dim=50, activation = 'relu'))

models.add(Dense(4, activation = 'relu'))

models.add(Dense(2, activation = 'softmax'))
models.compile (loss='sparse_binary_crossentropy')
                d_error', optimizer = 'adam', metrics = ['accuracy'])
models.fit(X_train, y_train, epochs = 50, batch_size = 100,)

ValueError: Error when checking target: expected dense_79 to have shape (2,) but got array with shape (1,)

In [281]:
predi = models.predict_proba(X_test)

In [282]:
print(predi[0:17])
predic = np.argmax(predi, axis = 1)

[[0.9022666  0.09773345]
 [0.62410575 0.37589428]
 [0.6672431  0.33275688]
 [0.55683637 0.44316363]
 [0.96612394 0.03387601]
 [0.3645792  0.6354208 ]
 [0.9566681  0.0433319 ]
 [0.94448876 0.05551132]
 [0.5224133  0.4775867 ]
 [0.9848862  0.01511375]
 [0.17385697 0.82614297]
 [0.9953035  0.00469655]
 [0.56873393 0.43126604]
 [0.54343015 0.45656994]
 [0.8018014  0.19819868]
 [0.4620834  0.5379166 ]
 [0.9959111  0.0040889 ]]

In [283]:
from sklearn.metrics import roc_auc_score
accurac = roc_auc_score(y_test , predic)
print ('Accuracy: %.2f%%' % (accurac * 100.0))

Accuracy: 67.74%

In [100]:
#my logistic regresion model
from sklearn.linear_model import LogisticRegression

In [222]:
mo = LogisticRegression(solver = 'liblinear', random_state = 3, C = 11.0, max_iter = 100)

In [223]:
mo.fit(X_train, y_train)

LogisticRegression(C=11.0, random_state=3, solver='liblinear')

In [224]:
p = mo.predict_proba(X_test)

In [225]:
pe = np.argmax(p, axis = 1)

In [226]:
from sklearn.metrics import roc_auc_score
accurc = roc_auc_score(y_test , pe)
print ('Accuracy: %.2f%%' % (accurc * 100.0))

Accuracy: 66.33%

In [135]:
#so this is how to use weighted average
finalpred = (predi*0.3+pre*0.3+ pred*0.4 )

In [136]:
finalpred

array([[0.9042535 , 0.09574655],
       [0.70396678, 0.29603325],
       [0.47668509, 0.52331495],
       ...,
       [0.99156374, 0.00843627],
       [0.99024896, 0.00975103],
       [0.71104188, 0.28895812]])

In [137]:
pr = np.argmax(finalpred, axis = 1)
ac = roc_auc_score(y_test , pr)
print ('Accuracy: %.2f%%' % (ac * 100.0))

Accuracy: 69.27%

In [32]:
#my catboost model, please help me adjust this one
import catboost
from catboost import CatBoostClassifier

In [33]:
mu = CatBoostClassifier(iterations = 50, depth = 11, learning_rate = 0.1, loss_function = 'Logloss')
fin = mu.fit(X_train, y_train, early_stopping_rounds = 200, eval_set = [(X_test, y_test)])

0:	learn: 0.6276067	test: 0.6296937	best: 0.6296937 (0)	total: 1.25s	remaining: 1m 1s
1:	learn: 0.5795415	test: 0.5832403	best: 0.5832403 (1)	total: 2.08s	remaining: 50s
2:	learn: 0.5413712	test: 0.5465912	best: 0.5465912 (2)	total: 2.86s	remaining: 44.9s
3:	learn: 0.5110830	test: 0.5190047	best: 0.5190047 (3)	total: 3.69s	remaining: 42.4s
4:	learn: 0.4885119	test: 0.4980014	best: 0.4980014 (4)	total: 4.62s	remaining: 41.6s
5:	learn: 0.4707535	test: 0.4828764	best: 0.4828764 (5)	total: 5.61s	remaining: 41.1s
6:	learn: 0.4558660	test: 0.4693469	best: 0.4693469 (6)	total: 6.39s	remaining: 39.3s
7:	learn: 0.4445902	test: 0.4599870	best: 0.4599870 (7)	total: 7.14s	remaining: 37.5s
8:	learn: 0.4341182	test: 0.4521075	best: 0.4521075 (8)	total: 7.86s	remaining: 35.8s
9:	learn: 0.4261453	test: 0.4466207	best: 0.4466207 (9)	total: 8.62s	remaining: 34.5s
10:	learn: 0.4199025	test: 0.4418152	best: 0.4418152 (10)	total: 9.44s	remaining: 33.5s
11:	learn: 0.4142743	test: 0.4379226	best: 0.4379226 (11)	total: 10.2s	remaining: 32.4s
12:	learn: 0.4098957	test: 0.4345376	best: 0.4345376 (12)	total: 11s	remaining: 31.2s
13:	learn: 0.4055139	test: 0.4317545	best: 0.4317545 (13)	total: 11.8s	remaining: 30.4s
14:	learn: 0.4013687	test: 0.4295885	best: 0.4295885 (14)	total: 12.7s	remaining: 29.6s
15:	learn: 0.3983778	test: 0.4280170	best: 0.4280170 (15)	total: 13.6s	remaining: 28.9s
16:	learn: 0.3957755	test: 0.4266012	best: 0.4266012 (16)	total: 14.5s	remaining: 28.1s
17:	learn: 0.3919996	test: 0.4251600	best: 0.4251600 (17)	total: 15.4s	remaining: 27.5s
18:	learn: 0.3893940	test: 0.4242151	best: 0.4242151 (18)	total: 16.3s	remaining: 26.5s
19:	learn: 0.3861859	test: 0.4232266	best: 0.4232266 (19)	total: 17s	remaining: 25.6s
20:	learn: 0.3835701	test: 0.4221744	best: 0.4221744 (20)	total: 17.8s	remaining: 24.5s
21:	learn: 0.3807062	test: 0.4213262	best: 0.4213262 (21)	total: 18.6s	remaining: 23.6s
22:	learn: 0.3786032	test: 0.4205445	best: 0.4205445 (22)	total: 19.3s	remaining: 22.7s
23:	learn: 0.3764829	test: 0.4198721	best: 0.4198721 (23)	total: 20s	remaining: 21.7s
24:	learn: 0.3749244	test: 0.4193162	best: 0.4193162 (24)	total: 20.7s	remaining: 20.7s
25:	learn: 0.3731520	test: 0.4187975	best: 0.4187975 (25)	total: 21.4s	remaining: 19.7s
26:	learn: 0.3707996	test: 0.4185450	best: 0.4185450 (26)	total: 22.1s	remaining: 18.8s
27:	learn: 0.3690301	test: 0.4183149	best: 0.4183149 (27)	total: 22.8s	remaining: 17.9s
28:	learn: 0.3683052	test: 0.4180102	best: 0.4180102 (28)	total: 23.6s	remaining: 17.1s
29:	learn: 0.3664534	test: 0.4176692	best: 0.4176692 (29)	total: 24.5s	remaining: 16.3s
30:	learn: 0.3653937	test: 0.4174119	best: 0.4174119 (30)	total: 25.4s	remaining: 15.5s
31:	learn: 0.3632857	test: 0.4171019	best: 0.4171019 (31)	total: 26.2s	remaining: 14.7s
32:	learn: 0.3620345	test: 0.4169610	best: 0.4169610 (32)	total: 27s	remaining: 13.9s
33:	learn: 0.3609086	test: 0.4169013	best: 0.4169013 (33)	total: 27.8s	remaining: 13.1s
34:	learn: 0.3593241	test: 0.4165878	best: 0.4165878 (34)	total: 28.8s	remaining: 12.3s
35:	learn: 0.3572215	test: 0.4164636	best: 0.4164636 (35)	total: 29.7s	remaining: 11.6s
36:	learn: 0.3562714	test: 0.4162871	best: 0.4162871 (36)	total: 30.5s	remaining: 10.7s
37:	learn: 0.3547004	test: 0.4163240	best: 0.4162871 (36)	total: 31.2s	remaining: 9.85s
38:	learn: 0.3531269	test: 0.4162319	best: 0.4162319 (38)	total: 31.9s	remaining: 8.99s
39:	learn: 0.3521531	test: 0.4162286	best: 0.4162286 (39)	total: 32.6s	remaining: 8.14s
40:	learn: 0.3508627	test: 0.4162100	best: 0.4162100 (40)	total: 33.4s	remaining: 7.32s
41:	learn: 0.3500213	test: 0.4159912	best: 0.4159912 (41)	total: 34.2s	remaining: 6.51s
42:	learn: 0.3486587	test: 0.4160228	best: 0.4159912 (41)	total: 35.1s	remaining: 5.71s
43:	learn: 0.3479595	test: 0.4159314	best: 0.4159314 (43)	total: 35.9s	remaining: 4.9s
44:	learn: 0.3466836	test: 0.4158182	best: 0.4158182 (44)	total: 36.9s	remaining: 4.1s
45:	learn: 0.3457918	test: 0.4156130	best: 0.4156130 (45)	total: 37.8s	remaining: 3.29s
46:	learn: 0.3448306	test: 0.4155816	best: 0.4155816 (46)	total: 38.8s	remaining: 2.48s
47:	learn: 0.3438870	test: 0.4155238	best: 0.4155238 (47)	total: 39.6s	remaining: 1.65s
48:	learn: 0.3417361	test: 0.4155285	best: 0.4155238 (47)	total: 40.4s	remaining: 824ms
49:	learn: 0.3406041	test: 0.4155847	best: 0.4155238 (47)	total: 41.1s	remaining: 0us

bestTest = 0.4155238472
bestIteration = 47

Shrink model to first 48 iterations.

In [34]:
prec = fin.predict_proba(X_test)

In [37]:
ma =  np.argmax(prec, axis = 1)

In [40]:
from sklearn.metrics import roc_auc_score
accu= roc_auc_score(y_test , ma)
print('Accuracy: %.2f%%' % (accu * 100.0))

Accuracy: 67.85%

In [ ]:
#please help me adjust anything you feel should be
#and please help me put the concept of me using my test set and the samplesubmission, thanks so much